export const TICKETS_COLLECTION = import.meta.env.VITE_TICKETS_COLLECTION;
export const USERS_COLLECTION = import.meta.env.VITE_USERS_COLLECTION;
export const APPLICATIONS_COLLECTION = import.meta.env
	.VITE_APPLICATIONS_COLLECTION;
export const APPLICATION_DRAFTS_COLLECTION = import.meta.env
	.VITE_APPLICATION_DRAFTS_COLLECTION;
export const RSVP_COLLECTION = import.meta.env.VITE_RSVP_COLLECTION;
export const HACKATHON_METADATA_COLLECTION = import.meta.env
	.VITE_HACKATHON_METADATA_COLLECTION;
