export const TICKETS_COLLECTION = import.meta.env.VITE_TICKETS_COLLECTION;
export const USERS_COLLECTION = import.meta.env.VITE_USERS_COLLECTION;
export const APPLICATIONS_COLLECTION = import.meta.env
	.VITE_APPLICATIONS_COLLECTION;
export const RSVP_COLLECTION = import.meta.env.VITE_RSVP_COLLECTION;
